name: CI
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cached Dependencies action
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cached-dependencies
        uses: ./.github/actions/dependencies-cache
        with:
          caching: 'false'
      - name: Lint
        run: yarn lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cached Dependencies action
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cached-dependencies
        uses: ./.github/actions/dependencies-cache
        with:
          caching: 'false'
      - name: Build
        run: yarn build