name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cached Dependencies action
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cached-dependencies
        uses: ./.github/actions/dependencies-cache
        with:
          caching: 'false'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_ACCESS_TOKEN }}